import React, { useState } from "react";
import { ArrowRight, Bot, CheckCircle2, Eye, EyeOff, ShieldCheck } from "lucide-react";
import { login, register } from "../services/api";

export default function AuthView({ onAuthenticated }) {
  const [mode, setMode] = useState("login"), [showPassword, setShowPassword] = useState(false);
  const [form, setForm] = useState({ name: "", email: "", password: "" }), [error, setError] = useState(""), [loading, setLoading] = useState(false);
  const update = (key, value) => setForm(current => ({ ...current, [key]: value }));
  const submit = async e => { e.preventDefault(); setError(""); setLoading(true); try { const result = mode === "login" ? await login(form.email, form.password) : await register(form.name, form.email, form.password); onAuthenticated(result); } catch (err) { setError(err.message); } finally { setLoading(false); } };
  return <div className="auth-shell">
    <section className="auth-showcase"><div className="brand"><Bot size={22}/><span>Edu<span>Fund</span></span></div><div className="showcase-copy"><span className="eyebrow">YOUR FUNDING, MADE CLEAR</span><h1>Education should never stop at affordability.</h1><p>Discover verified opportunities, build a winning funding plan, and manage every application in one calm workspace.</p><div className="trust-list"><div><CheckCircle2/> Smart eligibility matching</div><div><CheckCircle2/> Funding gap planner</div><div><CheckCircle2/> Human-reviewed application support</div></div></div><div className="showcase-note"><ShieldCheck size={18}/><span>Built for students. Decisions stay in your hands.</span></div></section>
    <section className="auth-panel"><div className="auth-card"><div className="mobile-brand"><Bot size={20}/> Edu<span>Fund</span></div><span className="eyebrow">{mode === "login" ? "WELCOME BACK" : "GET STARTED"}</span><h2>{mode === "login" ? "Sign in to your workspace" : "Create your student account"}</h2><p className="auth-subtitle">{mode === "login" ? "Continue planning your education funding." : "It takes less than a minute to begin."}</p><form onSubmit={submit}>{mode === "register" && <label>Full name<input required value={form.name} onChange={e => update("name", e.target.value)} placeholder="Your name"/></label>}<label>Email address<input required type="email" value={form.email} onChange={e => update("email", e.target.value)} placeholder="you@example.com"/></label><label>Password<div className="password-input"><input required minLength="8" type={showPassword ? "text" : "password"} value={form.password} onChange={e => update("password", e.target.value)} placeholder="At least 8 characters"/><button type="button" onClick={() => setShowPassword(!showPassword)}>{showPassword ? <EyeOff size={18}/> : <Eye size={18}/>}</button></div></label>{error && <div className="auth-error">{error}</div>}<button className="auth-submit" disabled={loading}>{loading ? "Please wait…" : mode === "login" ? "Sign in" : "Create account"}<ArrowRight size={18}/></button></form><div className="auth-switch">{mode === "login" ? "New to EduFund?" : "Already have an account?"}<button onClick={() => { setMode(mode === "login" ? "register" : "login"); setError(""); }}>{mode === "login" ? "Create an account" : "Sign in"}</button></div></div></section></div>;
}
