from typing import Optional, List, Dict, Any
from models import (
    StudentProfile, 
    Opportunity, 
    AutopilotDraftResponse,
    DraftRefineRequest,
    DraftRefineResponse,
    DocumentAuditRequest,
    DocumentAuditResponse
    , DraftEvidenceRequest, DraftEvidenceResponse, EvidenceFinding
)
from data.opportunities import get_opportunity_by_id

class AutopilotAgent:
    def __init__(self):
        self.agent_name = "Application Autopilot Agent"

    def prepare_application(
        self,
        opp_id: str,
        prompt_index: int,
        profile: Optional[StudentProfile]
    ) -> AutopilotDraftResponse:
        opp = get_opportunity_by_id(opp_id)
        if not opp:
            raise ValueError(f"Opportunity ID '{opp_id}' not found.")

        if not profile:
            profile = StudentProfile()

        missing_info = []
        if "Income Certificate" in opp.required_documents:
            inc = profile.financial_constraints.get("annual_family_income_inr")
            if not inc:
                missing_info.append("Verified Family Income Certificate / Tax Return")
        if "Official Transcript" in opp.required_documents or "10th & 12th Marksheets" in opp.required_documents:
            if not profile.academic_profile.get("gpa"):
                missing_info.append("Official Academic Transcript Document")
        if "Portfolio / GitHub" in opp.required_documents:
            if not any("github" in a.lower() or "hackathon" in a.lower() for a in profile.achievements):
                missing_info.append("Portfolio / GitHub URL Link")

        prompts = opp.essay_prompts if opp.essay_prompts else ["Why are you the ideal candidate for this funding opportunity?"]
        selected_prompt = prompts[min(prompt_index, len(prompts) - 1)]

        achievements_str = ", ".join(profile.achievements)
        interests_str = ", ".join(profile.interests)

        gpa_value = profile.academic_profile.get("gpa", 3.8)
        gpa_scale = profile.academic_profile.get("max_gpa", 4.0)
        draft = (
            f"As a dedicated {profile.education_level} student specializing in {profile.course} with a GPA of "
            f"{gpa_value}/{gpa_scale}, I am writing to apply for the {opp.title}.\n\n"
            f"My academic journey is driven by a deep passion for {interests_str}. Throughout my studies, I have consistently "
            f"striven for excellence, as demonstrated by my key achievements including: {achievements_str}.\n\n"
            f"Receiving the {opp.title} from {opp.provider} would provide vital support for my target educational expenses "
            f"(annual target cost of ₹{profile.financial_constraints.get('target_annual_cost_inr', 120000):,}), allowing me to "
            f"focus entirely on technical innovation and research rather than financial constraints. I look forward to contributing "
            f"back to the community through leadership and impactful projects."
        )

        checklist = []
        for doc in opp.required_documents:
            is_ready = doc not in missing_info
            checklist.append({
                "item": doc,
                "type": "DOCUMENT",
                "status": "READY" if is_ready else "PENDING_UPLOAD",
                "notes": "Verified in profile" if is_ready else "Action required by student"
            })

        checklist.append({
            "item": "Tailored Statement of Purpose / Essay Draft",
            "type": "ESSAY",
            "status": "DRAFT_PREPARED",
            "notes": "Generated by Autopilot Agent; requires student review."
        })
        checklist.append({
            "item": "Final Human Review & Safety Sign-off",
            "type": "SAFETY_CONTROL",
            "status": "PENDING_STUDENT_APPROVAL",
            "notes": "Safety control: AI will not submit financial forms without student explicit authorization."
        })

        return AutopilotDraftResponse(
            opportunity_id=opp.id,
            opportunity_title=opp.title,
            prompt=selected_prompt,
            missing_information=missing_info,
            application_checklist=checklist,
            draft_response=draft,
            submission_safety_passed=True
        )

    def refine_draft(self, req: DraftRefineRequest) -> DraftRefineResponse:
        instr = req.instruction.lower()
        draft = req.current_draft

        if "persuasive" in instr or "impact" in instr:
            refined = (
                "DEEP IMPACT REFINEMENT:\n" + draft + 
                "\n\nFurthermore, my track record in high-stakes hackathons and open-source contributions demonstrates "
                "my relentless drive to translate technical research into tangible, real-world societal impact."
            )
            style = "High Impact & Persuasive"
        elif "academic" in instr or "rigor" in instr:
            refined = (
                "ACADEMIC RIGOR REFINEMENT:\n" + draft + 
                "\n\nMy analytical foundation in algorithmic complexity, machine learning architectures, and empirical research "
                "positions me to excel in advanced research endeavors."
            )
            style = "Academic & Scholarly"
        elif "shorten" in instr or "concise" in instr:
            words = draft.split()
            shortened = " ".join(words[:min(100, len(words))]) + "..."
            refined = "CONCISE SUMMARY REFINEMENT:\n" + shortened
            style = "Concise (<100 words)"
        else:
            refined = draft + "\n\n[Refined with enhanced technical specificity and career clarity.]"
            style = "Balanced Professional"

        word_cnt = len(refined.split())
        mins = round(word_cnt / 200.0, 1)

        return DraftRefineResponse(
            refined_draft=refined,
            word_count=word_cnt,
            reading_time_mins=max(0.5, mins),
            applied_style=style
        )

    def audit_documents(self, req: DocumentAuditRequest) -> DocumentAuditResponse:
        opp = get_opportunity_by_id(req.opportunity_id)
        required = opp.required_documents if opp else ["10th & 12th Marksheets", "Income Certificate"]

        uploaded_names = [f.lower() for f in req.uploaded_files]
        verified = []
        missing = []

        for doc in required:
            doc_lower = doc.lower()
            found = any(u in doc_lower or doc_lower in u for u in uploaded_names)
            if found:
                verified.append({
                    "document": doc,
                    "file_name": doc.replace(" ", "_").lower() + ".pdf",
                    "status": "VERIFIED_VALID",
                    "confidence": 98.5
                })
            else:
                missing.append(doc)

        status = "PASSED" if len(missing) == 0 else "PENDING"
        notes = f"Audited {len(req.uploaded_files)} uploaded files against {len(required)} opportunity rules. "
        if missing:
            notes += f"Missing: {', '.join(missing)}."
        else:
            notes += "All required documents verified successfully!"

        return DocumentAuditResponse(
            verification_status=status,
            verified_files=verified,
            missing_requirements=missing,
            audit_notes=notes
        )

    def check_draft_evidence(self, req: DraftEvidenceRequest) -> DraftEvidenceResponse:
        draft = req.draft_text.lower()
        profile = req.student_profile
        known_facts = [profile.course, str(profile.academic_profile.get("gpa", "")), *profile.achievements, *profile.interests]
        findings = []
        for fact in known_facts:
            fact = str(fact).strip()
            if fact and fact.lower() in draft:
                findings.append(EvidenceFinding(claim=fact, status="SUPPORTED", detail="This claim is present in your saved profile."))
        risk_phrases = ["national", "international", "published", "led", "founded", "awarded", "first", "best"]
        for sentence in [s.strip() for s in req.draft_text.replace("\n", " ").split(".") if s.strip()]:
            if any(word in sentence.lower() for word in risk_phrases) and not any(str(f).lower() in sentence.lower() for f in known_facts if str(f)):
                findings.append(EvidenceFinding(claim=sentence[:140], status="REVIEW", detail="This may be a strong claim not directly supported by your saved profile. Add evidence or revise it."))
        return DraftEvidenceResponse(supported_count=len([f for f in findings if f.status == "SUPPORTED"]), review_count=len([f for f in findings if f.status == "REVIEW"]), findings=findings)
